#!/bin/bash
PATH=./node_modules/.bin:$PATH

# cd client
cd $(dirname $0)/..

# output folder
TARGET=../dist
[[ "$1" != "" ]] || TARGET=$1
[ -d $TARGET ] || mkdir -p $TARGET


cp -rvu src/public/* $TARGET/

./scripts/build-templates
browserify -d src/app.js -t babelify -t envify -o $TARGET/app.js -v
myth src/styles/app.css $TARGET/app.css

# ./scripts/lint-elements.sh
# mochify --transform babelify --reporter spec ./test/index.js
