#!/bin/bash

all=`dirname $0`/../src/templates/*.html

for template in $all; do
	target="$(dirname $template)/$(basename -s .html $template).js"
  html=`cat $template`
  echo html | grep '\<([A-Z]\S*).*\>'
	(
    echo "import { element } from 'deku'";
    echo 'export default {';
    echo -e "  render: ({props}) => $html"; echo '}'
  )> $target
done
