#!/bin/bash

cd $(dirname $0)/..

target=$HOME/.klouds/bundled

PATH=./node_modules/.bin:$PATH

export NODE_ENV=development
export API="http://localhost:8080"

if [ ! -d $target ]; then
    mkdir -p $target
fi

cp -rvu src/public/* $target/

# ./scripts/build-templates src/templates/*.html
# echo Done generating templates

browserify -d src/app.js -t babelify -o $target/app.js -v
echo Done generating app.js

myth src/styles/app.css $target/app.css
echo Done generating app.css

# ./scripts/lint-elements.sh
# mochify --transform babelify --reporter spec ./test/index.js

echo Done building
