#!/bin/bash

babel-node -e <<EOF
import { appsDb, appsDisabledDb } from '../lib/db'

appsDb.push({ name: 'Flarum', repo: 'flarum/flarum' })
appsDb.push({ name: 'wordpress', repo: 'wordpress/wordpress' })
appsDb.push({ name: 'ReactionCommerce', repo: 'reactioncommerce/reaction' })
appsDb.push({ name: 'Gogs', repo: 'gogits/gogs' })
appsDb.push({ name: 'Journey', repo: 'kabukky/journey' })
appsDisabledDb.push({ name: 'Sandstorm.io' })
appsDisabledDb.push({ name: 'Ghost' })
appsDisabledDb.push({ name: 'ethersheet' })
appsDisabledDb.push({ name: 'rizzoma' })
appsDisabledDb.push({ name: 'junta' })
appsDisabledDb.push({ name: 'metamaps' })
appsDisabledDb.push({ name: 'apache wave' })
appsDisabledDb.push({ name: 'gitorius' })
appsDisabledDb.push({ name: 'etherpad' })
appsDisabledDb.push({ name: 'taiga.io' })
appsDisabledDb.push({ name: 'ownCloud' })
appsDisabledDb.push({ name: 'loomio' })
appsDisabledDb.push({ name: 'Kaiwa' })
appsDisabledDb.push({ name: 'Apache OFBiz' })
appsDisabledDb.push({ name: 'Apache Roller' })
appsDisabledDb.push({ name: 'Jclouds' })
appsDisabledDb.push({ name: 'Codiad' })
appsDisabledDb.push({ name: 'Apache Tomcat' })
appsDisabledDb.push({ name: 'Streisand' })
appsDisabledDb.push({ name: 'Diaspora' })
appsDisabledDb.push({ name: 'Discourse' })
appsDisabledDb.push({ name: 'Brooklyn' })
appsDisabledDb.push({ name: 'Vault' })
appsDisabledDb.push({ name: 'HabitRPG' })
appsDisabledDb.push({ name: 'Preconfigured, Prethemed Jekyll 100% free for Github pages' })
appsDisabledDb.push({ name: 'Syncthing' })
appsDisabledDb.push({ name: 'piwik' })
appsDisabledDb.push({ name: 'invoice-ninja' })
appsDisabledDb.push({ name: 'Hugo preconfigured & prethemed like Jekyll & optimized for GH pages' })
appsDisabledDb.push({ name: 'gocd' })
appsDisabledDb.push({ name: 'Sylius' })
appsDisabledDb.push({ name: 'gitlab-ci' })
appsDisabledDb.push({ name: 'Apache Spark' })
appsDisabledDb.push({ name: 'Graylog' })
appsDisabledDb.push({ name: 'OctoberCMS' })
appsDisabledDb.push({ name: 'Mermaid' })
appsDisabledDb.push({ name: 'Joomla' })
appsDisabledDb.push({ name: 'Medium-editor' })
appsDisabledDb.push({ name: 'Seafile' })
appsDisabledDb.push({ name: 'PrestaShop' })
appsDisabledDb.push({ name: 'Mapnik' })
appsDisabledDb.push({ name: 'hexo' })
appsDisabledDb.push({ name: 'druid-io/druid' })
appsDisabledDb.push({ name: 'sirius' })
appsDisabledDb.push({ name: 'OpenRefine' })
appsDisabledDb.push({ name: 'Phaser' })
appsDisabledDb.push({ name: 'vanilla' })
appsDisabledDb.push({ name: 'sandstorm.io' })
appsDisabledDb.push({ name: 'onionshare' })
appsDisabledDb.push({ name: 'exercism.io' })
appsDisabledDb.push({ name: 'tiddlywiki5' })
appsDisabledDb.push({ name: 'bitcore' })
appsDisabledDb.push({ name: 'Mail In A Box' })
appsDisabledDb.push({ name: 'opencart' })
appsDisabledDb.push({ name: 'libreboard' })
appsDisabledDb.push({ name: 'Taiga' })
appsDisabledDb.push({ name: 'OpenBazaar' })
appsDisabledDb.push({ name: 'codeboxide' })
appsDisabledDb.push({ name: 'paperwork' })
EOF
