#!/bin/babel-node

import { appsDb } from '../db'

appsDb('apps').push({ name: 'Flarum', repo: 'flarum/flarum' })
appsDb('apps').push({ name: 'wordpress', repo: 'wordpress/wordpress' })
appsDb('apps').push({ name: 'ReactionCommerce', repo: 'reactioncommerce/reaction' })
appsDb('apps').push({ name: 'Gogs', repo: 'gogits/gogs' })
appsDb('apps').push({ name: 'Journey', repo: 'kabukky/journey' })

appsDb('disabled').push({ name: 'Sandstorm.io' })
appsDb('disabled').push({ name: 'Ghost' })
appsDb('disabled').push({ name: 'ethersheet' })
appsDb('disabled').push({ name: 'rizzoma' })
appsDb('disabled').push({ name: 'junta' })
appsDb('disabled').push({ name: 'metamaps' })
appsDb('disabled').push({ name: 'apache wave' })
appsDb('disabled').push({ name: 'gitorius' })
appsDb('disabled').push({ name: 'etherpad' })
appsDb('disabled').push({ name: 'taiga.io' })
appsDb('disabled').push({ name: 'ownCloud' })
appsDb('disabled').push({ name: 'loomio' })
appsDb('disabled').push({ name: 'Kaiwa' })
appsDb('disabled').push({ name: 'Apache OFBiz' })
appsDb('disabled').push({ name: 'Apache Roller' })
appsDb('disabled').push({ name: 'Jclouds' })
appsDb('disabled').push({ name: 'Codiad' })
appsDb('disabled').push({ name: 'Apache Tomcat' })
appsDb('disabled').push({ name: 'Streisand' })
appsDb('disabled').push({ name: 'Diaspora' })
appsDb('disabled').push({ name: 'Discourse' })
appsDb('disabled').push({ name: 'Brooklyn' })
appsDb('disabled').push({ name: 'Vault' })
appsDb('disabled').push({ name: 'HabitRPG' })
appsDb('disabled').push({ name: 'Preconfigured, Prethemed Jekyll 100% free for Github pages' })
appsDb('disabled').push({ name: 'Syncthing' })
appsDb('disabled').push({ name: 'piwik' })
appsDb('disabled').push({ name: 'invoice-ninja' })
appsDb('disabled').push({ name: 'Hugo preconfigured & prethemed like Jekyll & optimized for GH pages' })
appsDb('disabled').push({ name: 'gocd' })
appsDb('disabled').push({ name: 'Sylius' })
appsDb('disabled').push({ name: 'gitlab-ci' })
appsDb('disabled').push({ name: 'Apache Spark' })
appsDb('disabled').push({ name: 'Graylog' })
appsDb('disabled').push({ name: 'OctoberCMS' })
appsDb('disabled').push({ name: 'Mermaid' })
appsDb('disabled').push({ name: 'Joomla' })
appsDb('disabled').push({ name: 'Medium-editor' })
appsDb('disabled').push({ name: 'Seafile' })
appsDb('disabled').push({ name: 'PrestaShop' })
appsDb('disabled').push({ name: 'Mapnik' })
appsDb('disabled').push({ name: 'hexo' })
appsDb('disabled').push({ name: 'druid-io/druid' })
appsDb('disabled').push({ name: 'sirius' })
appsDb('disabled').push({ name: 'OpenRefine' })
appsDb('disabled').push({ name: 'Phaser' })
appsDb('disabled').push({ name: 'vanilla' })
appsDb('disabled').push({ name: 'sandstorm.io' })
appsDb('disabled').push({ name: 'onionshare' })
appsDb('disabled').push({ name: 'exercism.io' })
appsDb('disabled').push({ name: 'tiddlywiki5' })
appsDb('disabled').push({ name: 'bitcore' })
appsDb('disabled').push({ name: 'Mail In A Box' })
appsDb('disabled').push({ name: 'opencart' })
appsDb('disabled').push({ name: 'libreboard' })
appsDb('disabled').push({ name: 'Taiga' })
appsDb('disabled').push({ name: 'OpenBazaar' })
appsDb('disabled').push({ name: 'codeboxide' })
appsDb('disabled').push({ name: 'paperwork' })